apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 1
  progressDeadlineSeconds: 8
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - image: ghcr.io/dhpup/guestbook
        name: guestbook
        ports:
        - containerPort: 80
