apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-multi
spec:
  project: kargo-multi
  source:
    repoURL: https://github.com/dhpup/kargo-multi.git
    path: kargo-multi
  destination:
    server: https://b5bxdj947v9xturb-cplane.kargosvcs.akuity.cloud
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
